var telegram = require('../src/telegram'),
    logger = require('../src/logger'),
    utils = require('../src/utils'),
    app_cfg = require('./app'),
    entity_cfg = require('./entity'),
    ip = require('ip'),
    jsu = require('underscore'),
    weather = require('weather-js'),
    isSEmoji = require('is-standard-emoji'),
    unicode = require("emoji-unicode-map"),
    emoji = require("emoji-dictionary"),
    google = require('google'),
    queue = require('queue'),
    redis_node = require("redis"),
    multiline = require('multiline'),
    botan = require('botanio')(app_cfg.token_botan),
    Q = require("q"),
    request = require('request'),
    readline = require('readline'),
    datetime = require('node-datetime'),
    random = require("random-js")(),
    actions = require('../src/actions'),
    wit = require('../src/wit');

var _ = {
  ip: ip,
  jsu: jsu,
  weather: weather,
  isSEmoji: isSEmoji,
  unicode: unicode,
  emoji: emoji,
  google: google,
  queue: queue,
  redis_node: redis_node,
  multiline: multiline,
  botan: botan,
  Q: Q,
  random: random,
  request: request,
  readline: readline,
  datetime: datetime,
  wit: wit,
  actions: actions,
  telegram: telegram,
  logger: logger,
  utils: utils,
  app_cfg: app_cfg,
  entity_cfg: entity_cfg
}

module.exports = _;
